#!/bin/sh
#
# Start duplo
#
# Remote for Duplo
#

start() {
	echo -n "Starting duplo: "
	while true; do /usr/bin/duplo; /bin/sleep 1; done
	echo "OK"
}

stop() {
	echo -n "Stopping duplo: "
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
